namespace Bam.Server
{
    /// <summary>
    /// Associates an HTTP status code with a default response string and an optional handler function.
    /// </summary>
    public class HttpStatusCodeHandler
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HttpStatusCodeHandler"/> class with a default 200 OK response.
        /// </summary>
        public HttpStatusCodeHandler()
        {
            DefaultResponse = "OK";
            Code = 200;
            Handle = () => DefaultResponse;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HttpStatusCodeHandler"/> class with the specified code and default response.
        /// </summary>
        /// <param name="code">The HTTP status code.</param>
        /// <param name="defaultResponse">The default response string.</param>
        public HttpStatusCodeHandler(int code, string defaultResponse)
        {
            DefaultResponse = defaultResponse;
            Code = code;
            Handle = () => DefaultResponse;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HttpStatusCodeHandler"/> class with the specified code and handler function.
        /// </summary>
        /// <param name="code">The HTTP status code.</param>
        /// <param name="handler">A function that produces the response string.</param>
        public HttpStatusCodeHandler(int code, Func<string> handler)
        {
            Code = code;
            Handle = handler;
        }
        string _defaultResponse;
        /// <summary>
        /// Gets or sets the default response string. If not set, it is lazily generated by the Handle function.
        /// </summary>
        public string DefaultResponse
        {
            get
            {
                if (string.IsNullOrEmpty(_defaultResponse) && Handle != null)
                {
                    _defaultResponse = Handle();
                }
                return _defaultResponse;
            }
            set => _defaultResponse = value;
        }

        /// <summary>
        /// Gets or sets the HTTP status code.
        /// </summary>
        public int Code { get; set; }

        /// <summary>
        /// Gets or sets the function that produces the response string.
        /// </summary>
        public Func<string> Handle { get; set; }

        /// <summary>
        /// Gets the <see cref="HttpStatusCodeHandler"/> for the specified status code, or a new handler with an empty response.
        /// </summary>
        /// <param name="code">The HTTP status code.</param>
        /// <returns>The corresponding handler.</returns>
        public static HttpStatusCodeHandler Get(int code)
        {
            if (Defaults.ContainsKey(code))
            {
                return Defaults[code];
            }
            return new HttpStatusCodeHandler(code, string.Empty);
        }

        static Dictionary<int, HttpStatusCodeHandler> _defaults;
        static object _defaultLock = new object();
        /// <summary>
        /// Gets the dictionary of default HTTP status code handlers for common status codes.
        /// </summary>
        public static Dictionary<int, HttpStatusCodeHandler> Defaults
        {
            get
            {
                return _defaultLock.DoubleCheckLock(ref _defaults, () =>
                {
                    return new Dictionary<int, HttpStatusCodeHandler>
                    {
                        { 200, new HttpStatusCodeHandler() },
                        { 400, new HttpStatusCodeHandler(400, "Bad Request") },
                        { 401, new HttpStatusCodeHandler(401, "Unauthorized") },
                        { 404, new HttpStatusCodeHandler(404, "Not Found") },
                        { 500, new HttpStatusCodeHandler(500, "Server Error") }
                    };
                });
            }
        }
    }
}
